# Generated by Django 6.0.2 on 2026-06-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_aimdealer_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order', 'name']},
        ),
    ]
