# TargetSiteStatusEvent — append-only audit log for status changes (manual + AIM sync).
# Historical Inactive rows are seeded in 0016_backfill_target_site_status_events.
# Generated by Django 6.0.2 on 2026-06-15 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_reactivate_sites_for_active_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSiteStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('account_sync', 'Account sync'), ('account_reactivate', 'Account reactivated'), ('system', 'System')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_site_status_events', to=settings.AUTH_USER_MODEL)),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='project.targetsite')),
            ],
            options={
                'verbose_name': 'Target site status event',
                'verbose_name_plural': 'Target site status events',
                'ordering': ['-created_at'],
            },
        ),
    ]
